runtime: python312  # Укажите версию Python, которую вы используете
entrypoint: gunicorn --worker-class aiohttp.GunicornWebWorker --timeout 120 main:app  # Изменена точка входа

# Дополнительные настройки
env_variables:
  EXAMPLE_ENV_VAR: 'value'